{{ if or (and .Values.mgmtclustercert (eq .Values.mgmtclustercert.enabled true)) (and .Values.standalonecluster (eq .Values.standalonecluster.enabled true))}}
apiVersion: projectcalico.org/v3
kind: LicenseKey
metadata:
  creationTimestamp: null
  name: default
spec:
  certificate: |+
    -----BEGIN CERTIFICATE-----
    MIIFxjCCA66gAwIBAgIQVq3rz5D4nQF1fIgMEh71DzANBgkqhkiG9w0BAQsFADCB
    tTELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh
    biBGcmFuY2lzY28xFDASBgNVBAoTC1RpZ2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1
    cml0eSA8c2lydEB0aWdlcmEuaW8+MT8wPQYDVQQDEzZUaWdlcmEgRW50aXRsZW1l
    bnRzIEludGVybWVkaWF0ZSBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkwHhcNMTgwNDA1
    MjEzMDI5WhcNMjAxMDA2MjEzMDI5WjCBnjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
    CkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBGcmFuY2lzY28xFDASBgNVBAoTC1Rp
    Z2VyYSwgSW5jMSIwIAYDVQQLDBlTZWN1cml0eSA8c2lydEB0aWdlcmEuaW8+MSgw
    JgYDVQQDEx9UaWdlcmEgRW50aXRsZW1lbnRzIENlcnRpZmljYXRlMIIBojANBgkq
    hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAwg3LkeHTwMi651af/HEXi1tpM4K0LVqb
    5oUxX5b5jjgi+LHMPzMI6oU+NoGPHNqirhAQqK/k7W7r0oaMe1APWzaCAZpHiMxE
    MlsAXmLVUrKg/g+hgrqeije3JDQutnN9h5oZnsg1IneBArnE/AKIHH8XE79yMG49
    LaKpPGhpF8NoG2yoWFp2ekihSohvqKxa3m6pxoBVdwNxN0AfWxb60p2SF0lOi6B3
    hgK6+ILy08ZqXefiUs+GC1Af4qI1jRhPkjv3qv+H1aQVrq6BqKFXwWIlXCXF57CR
    hvUaTOG3fGtlVyiPE4+wi7QDo0cU/+Gx4mNzvmc6lRjz1c5yKxdYvgwXajSBx2pw
    kTP0iJxI64zv7u3BZEEII6ak9mgUU1CeGZ1KR2Xu80JiWHAYNOiUKCBYHNKDCUYl
    RBErYcAWz2mBpkKyP6hbH16GjXHTTdq5xENmRDHabpHw5o+21LkWBY25EaxjwcZa
    Y3qMIOllTZ2iRrXu7fSP6iDjtFCcE2bFAgMBAAGjZzBlMA4GA1UdDwEB/wQEAwIF
    oDATBgNVHSUEDDAKBggrBgEFBQcDAjAdBgNVHQ4EFgQUIY7LzqNTzgyTBE5efHb5
    kZ71BUEwHwYDVR0jBBgwFoAUxZA5kifzo4NniQfGKb+4wruTIFowDQYJKoZIhvcN
    AQELBQADggIBAAK207LaqMrnphF6CFQnkMLbskSpDZsKfqqNB52poRvUrNVUOB1w
    3dSEaBUjhFgUU6yzF+xnuH84XVbjD7qlM3YbdiKvJS9jrm71saCKMNc+b9HSeQAU
    DGY7GPb7Y/LG0GKYawYJcPpvRCNnDLsSVn5N4J1foWAWnxuQ6k57ymWwcddibYHD
    OPakOvO4beAnvax3+K5dqF0bh2Np79YolKdIgUVzf4KSBRN4ZE3AOKlBfiKUvWy6
    nRGvu8O/8VaI0vGaOdXvWA5b61H0o5cm50A88tTm2LHxTXynE3AYriHxsWBbRpoM
    oFnmDaQtGY67S6xGfQbwxrwCFd1l7rGsyBQ17cuusOvMNZEEWraLY/738yWKw3qX
    U7KBxdPWPIPd6iDzVjcZrS8AehUEfNQ5yd26gDgW+rZYJoAFYv0vydMEyoI53xXs
    cpY84qV37ZC8wYicugidg9cFtD+1E0nVgOLXPkHnmc7lIDHFiWQKfOieH+KoVCbb
    zdFu3rhW31ygphRmgszkHwApllCTBBMOqMaBpS8eHCnetOITvyB4Kiu1/nKvVxhY
    exit11KQv8F3kTIUQRm0qw00TSBjuQHKoG83yfimlQ8OazciT+aLpVaY8SOrrNnL
    IJ8dHgTpF9WWHxx04DDzqrT7Xq99F9RzDzM7dSizGxIxonoWcBjiF6n5
    -----END CERTIFICATE-----

  token: eyJhbGciOiJBMTI4R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4R0NNIiwiaXYiOiJFQU92T0lORVRvZFl6OE1sIiwidGFnIjoic3Y2dUVPZnB2SERuSjBENU5ZOXR0USIsInR5cCI6IkpXVCJ9.rGe2OnyhL8wv1dZZAUo9ww.2o8H35v1ieDfTfOM.lzeedZ1UJFAn_229K8_QcXAxoINZvi3J6tepztOmw0otrOujW9SdVuZK9bjdjxwj2CioBu9zANi09yacG5hrW7C65-kcjEmjtOKA0JYaKorOjHGHTYAsjeRSpFNBVAadTch-wzYCC1v_b3Gu2RqmCB0yWLd8DlBeT1t1xgFxJP6ku_k4ZIv3sVjYSVicy04zlPskwGFHEXImrBIjBdOf2eXzmTeVcWrKI-bO0FtzrgA8oS6tPvhHIItLNFvP3wOhHda9II97GcWf30Mh7VsJTpZuCQI9VQNGY2O60sH778bt0MMtt8Kgx8GrCvrO5LOswM7Qvv4jAmcWB6picXpDUcfREDFlRe73Hnvf3UtvKiq3YvIRSHzbqyHkCKx0daMPJ6qcN-TtrdTLctKw7364bzLAggzqx5TXvk1oP69o6uSdQqlArcfntXn88iKjzZhbOr8LiptfXeGq5ooe1QRZ6YFjv756uob0RVkd3_EszQxVt-xQQ6kV1NXvgS2UStPwElaFjjJPjNNtW6PouH6PjFz39FUdvPmaDIfyhAsJMdY1wqRD_TQstR5DL-QH7DnvHIF6iNE7cguFqFp3SEryy4jVNsssGj_GSUJJzWu6VSFBIF5Aad0hzXokYw8CngsKVkvrweEsIuPbEQS7gkit7O0izDduNtF6WuxGORPA2Dw1xe3KTvPeluQDF-gQJO_Smbz2n-Y5vt_zUhokcCgc3aMHTxgEd4AVarNIJFD4dkmFH3DqFaI7tke7pGWisdF7PgiKLeT91I69g0WvKgcvHTDRq4tRqznHCdqaqo3gZZ7ZyI1-VBpaT7nj2mb_4hlvjb-TlHtLm7ND7Z7htsHSO4tiGVWMgVrNRHqMwmfxDfXz8dgijRRolYGbNBp5TZENWqFU_RyJSNwNOYz8cOIj2wZvl-A2p0TTdOlTZ5NMl2z1UIFQFE0lfOKgSMtAiFZeqhySp5B-wtzatPhKBXqLA8IQOOpIHvXz064twm3wSebXtXEfPPpdyGM7bbwh7HWUBUFiX0EFn0yfWcmw1R2Ca-pTcgjollCxsUXlTfPk24CQVrmQ7KJF2jwYGpALDEGWoX586pAtJ3VbL3bIUbT8xjle6u_leo6Iv9I.42KhWaEYDVJdzdRqBrqycA

{{ end }}
