apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tigera-manager-man
  namespace: tigera-manager
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: wrong.url.training.tigera.ca 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tigera-manager
            port:
              number: 9443
