{{ if and .Values.mgmtclustercert (eq .Values.mgmtclustercert.enabled true) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tigera-manager-mcm
  namespace: tigera-manager
  annotations:
    external-dns.alpha.kubernetes.io/hostname: leonargomcm.training.tigera.ca 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: leonargomcm.training.tigera.ca 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tigera-manager-mcm
            port:
              number: 9449
{{ end }}
