apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-enterprise-1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: day2-cluster
    namespace: tigera-operator
  source:
    path: charts/calico-enterprise
    repoURL: 'CHANGEME'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 35
      backoff:
        duration: 30s
        factor: 1
        maxDuration: 3m
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: beats.beat.k8s.elastic.co
      jsonPointers:
        - /spec
    - kind: PersistentVolume
      jsonPointers:
        - /spec/claimRef/resourceVersion
        - /spec/claimRef/uid
        - /status/lastPhaseTransitionTime
    - kind: Secret
      jsonPointers:
        - /data
    - kind: ManagedCluster
      name: '*'
      jsonPointers:
        - /spec
    - group: operator.tigera.io
      kind: DefaultFelixConfiguration
      jsonPointers:
        - /spec/flowLogsFlushInterval
    - group: projectcalico.org
      kind: FelixConfiguration
      jsonPointers:
        - /spec/flowLogsFlushInterval
