apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calico-ent-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  source:
    repoURL: 'https://github.com/tigera-cs/day2-gitops-workshop.git'
    path: charts/ingress-nginx
    targetRevision: HEAD
  destination:
    name: day2-cluster
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 50
      backoff:
        duration: 60s
        factor: 1
        maxDuration: 5m
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: beats.beat.k8s.elastic.co
      jsonPointers:
        - /spec
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: env-custom-configs-ingress-nginx-admission
    - group: networking.k8s.io
      kind: Ingress
      namespace: tigera-manager
      name: tigera-manager-man
    - group: networking.k8s.io
      kind: Ingress
      namespace: tigera-manager
      name: tigera-manager-mcm
    - group: projectcalico.org
      kind: LicenseKey
      name: default
