apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ce-standalone-app-of-apps
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argo-apps/calico-enterprise-standalone/dev-team-1
    repoURL: 'CHANGEME'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
  syncWaves:
  - name: wave1
    applications:
    - sealed-secrets
  - name: wave2
    applications:
    - calico-enterprise-1
  - name: wave3
    applications:
    - calico-ent-configs
  - name: wave4
    applications:
    - base-policies

