standalonecluster:
  enabled: true
tigera-operator:
  imagePullSecrets: # ideally we should not need this but there could be a bug in the helm-charts
    tigera-pull-secret: unusedvalue
  installation:
    enabled: true
    variant: TigeraSecureEnterprise
    imagePullSecrets:
      - name: tigera-pull-secret
    calicoNetwork:
      bgp: Enabled
      ipPools:
      - cidr: 10.48.0.0/24
        blockSize: 26
        encapsulation: None
        natOutgoing: Enabled

  monitor:
    enabled: true

  apiServer:
    enabled: true
