tigeraOperatorVersion: "3.19"
tigera-operator:
  imagePullSecrets:
    tigera-pull-secret: unusedvalue
  installation:
    enabled: true
    variant: TigeraSecureEnterprise
    imagePullSecrets:
      - name: tigera-pull-secret

  monitor:
    enabled: true

  apiServer:
    enabled: true

  compliance:
    enabled: false