standalonecluster:
  enabled: true
tigera-operator:
  imagePullSecrets: # ideally we should not need this but there could be a bug in the helm-charts
    tigera-pull-secret: unusedvalue
  installation:
    enabled: true
    variant: TigeraSecureEnterprise
    imagePullSecrets:
      - name: tigera-pull-secret

  monitor:
    enabled: true

  apiServer:
    enabled: true

  compliance:
    enabled: false

  defaultFelixConfiguration:
    enabled: false
    flowLogsFlushInterval: 10s